version: '3.8'
services:
  pmki:
    image: pmki:1.0.0
    build:
      context: ./1.0.0
    ports:
    - "1979:1979"
    volumes:
     - type: bind
       source: ./volumes/pmki-stdata
       target: /opt/pmki/data
    links:
    - pmki-graphdb
    - development-vocbench3
  pmki-graphdb:
    image: graphdb-with-st-sails:9.1.1-se
    build:
      context: ./vocbench3-docker/helpers/graphdb-with-st-sails
      args:
        st_version: "8.0"
        gdb_version: "9.1.1-se"
    ports:
     - "127.0.0.1:7200:7200"
    volumes:
     - type: bind
       source: ./volumes/pmki-gdbhome
       target: /opt/graphdb/home
  development-vocbench3:
    image: vocbench3:8.0.0
    build:
      context: ./vocbench3-docker/8.0.0
    ports:
    - "1980:1979"
    volumes:
     - type: bind
       source: ./volumes/development-stdata
       target: /opt/vocbench3/data
    links:
    - development-graphdb
  development-graphdb:
    image: graphdb-with-st-sails:9.1.1-se
    build:
      context: ./vocbench3-docker/helpers/graphdb-with-st-sails
      args:
        st_version: "8.0"
        gdb_version: "9.1.1-se"
    ports:
     - "127.0.0.1:7201:7200"
    volumes:
     - type: bind
       source: ./volumes/development-gdbhome
       target: /opt/graphdb/home