version: '3.8'
services:
  showvoc:
    image: showvoc:1.2.1
    build:
      context: ./1.2.1
    ports:
    - "1979:1979"
    volumes:
     - type: bind
       source: ./volumes/showvoc-stdata
       target: /opt/showvoc/data
    links:
    - showvoc-graphdb
    - development-vocbench3
  showvoc-graphdb:
    image: graphdb-with-st-sails:9.8.1-se
    build:
      context: ./vocbench3-docker/helpers/graphdb-with-st-sails
      args:
        st_version: "10.2"
        gdb_version: "9.8.1-se"
    ports:
     - "127.0.0.1:7200:7200"
    volumes:
     - type: bind
       source: ./volumes/showvoc-gdbhome
       target: /opt/graphdb/home
  development-vocbench3:
    image: vocbench3:10.0.0
    build:
      context: ./vocbench3-docker/10.2.0
    ports:
    - "1980:1979"
    volumes:
     - type: bind
       source: ./volumes/development-stdata
       target: /opt/vocbench3/data
    links:
    - development-graphdb
  development-graphdb:
    image: graphdb-with-st-sails:9.8.1-se
    build:
      context: ./vocbench3-docker/helpers/graphdb-with-st-sails
      args:
        st_version: "10.2"
        gdb_version: "9.8.1-se"
    ports:
     - "127.0.0.1:7201:7200"
    volumes:
     - type: bind
       source: ./volumes/development-gdbhome
       target: /opt/graphdb/home